"""Add bio column to users

Revision ID: b9656acaab57
Revises: 8420728118de
Create Date: 2026-01-31 18:04:02.006230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9656acaab57'
down_revision: Union[str, Sequence[str], None] = '8420728118de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_users', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instagram_users', 'bio')
    # ### end Alembic commands ###
