"""remove bio cilumn and add status column to users

Revision ID: 810bdaa6e986
Revises: b9656acaab57
Create Date: 2026-02-01 22:06:57.549079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810bdaa6e986'
down_revision: Union[str, Sequence[str], None] = 'b9656acaab57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_users', sa.Column('status', sa.String(length=20), server_default=sa.text("'new'"), nullable=False))
    op.drop_column('instagram_users', 'bio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instagram_users', sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('instagram_users', 'status')
    # ### end Alembic commands ###
